### ISSUE TITLE
Square Photos

### ISSUE THREAD

**Issue by robbyklein** [robbyklein/fruda#1]
Can I get square versions of these photos. Will be best to let CSS handle border-radius.

<img width="344" alt="screen shot 2015-08-09 at 12 37 23 pm" src="https://cloud.githubusercontent.com/assets/6813372/9156556/89433432-3e93-11e5-9c76-1c6c427a97fc.png">

**Comment by idigit** [comment]
![1](https://cloud.githubusercontent.com/assets/689114/9156610/bcb2c938-3ea5-11e5-9224-6d69fa6b045a.jpg)
![2](https://cloud.githubusercontent.com/assets/689114/9156613/bcb469aa-3ea5-11e5-94ff-dc47f0a7bdab.jpg)
![3](https://cloud.githubusercontent.com/assets/689114/9156612/bcb43d86-3ea5-11e5-995a-0632417d0f12.jpg)
![4](https://cloud.githubusercontent.com/assets/689114/9156611/bcb43ad4-3ea5-11e5-90af-318759054421.jpg)
![5](https://cloud.githubusercontent.com/assets/689114/9156614/bcb4673e-3ea5-11e5-83ba-4322c2cb1bf6.jpg)
